config/routes.rb
Takeout::Application.routes.draw do
  root :to => 'welcome#show'

  resource :welcome

  resource :settings do
    member do
      get 'scan'
      get 'music_scan'
      get 'movies_scan'
    end
  end

  resources :music_members do
    member do
      get 'artists'
    end
    collection do
      get 'performers'
    end
  end

  resources :music_credits

  resources :music_images

  resource :music, :controller => 'music' do
    member do
      get 'artists'
      get 'albums'
      get 'tracks'
      get 'songs'
    end
  end
  resources :music_categories
  resources :music_genres, :only => [:index, :show] do
    member do
      get 'artists'
      get 'albums'
      get 'tracks'
      get 'songs'
    end
  end
  resources :music_songs do
    member do
      get 'stream'
      get 'cover'
    end
  end
  resources :music_albums, :only => [:index, :show] do
    collection do
      get 'released'
      get 'modified'
      get 'added'
    end
  end
  resources :music_artists do
    member do
      get 'songs'
    end
  end
  resources :music_search, :only => [:index]

  resources :movie_members do
    member do
      get 'movies'
    end
    collection do
      get 'actors'
      get 'directors'
      get 'producers'
      get 'writers'
    end
  end
  match 'movie_actors' => 'movie_members#actors'
  match 'movie_directors' => 'movie_members#directors'
  match 'movie_producers' => 'movie_members#producers'
  match 'movie_writers' => 'movie_members#writers'

  resources :movies, :only => [:index, :show] do
    member do
      get 'credits'
      get 'cast'
      get 'genres'
      get 'images'
      get 'stream'
    end
    collection do
      get 'released'
      get 'modified'
      get 'added'
    end
  end
  resources :movie_credits, :only => [:index, :show]
  resources :movie_collections, :only => [:index, :show]
  resources :movie_images, :only => [:index, :show]
  resources :movie_genres, :only => [:index, :show] do
    member do
      get 'movies'
    end
  end

end

app/models/music_category.rb
class MusicCategory < ActiveRecord::Base
  belongs_to :music_genre
  belongs_to :music_song
end

app/controllers/music_categories_controller.rb
class MusicCategoriesController < ApplicationController
  # GET /music_categories
  # GET /music_categories.json
  def index
    @music_categories = MusicCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @music_categories }
    end
  end

  # GET /music_categories/1
  # GET /music_categories/1.json
  def show
    @music_category = MusicCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @music_category }
    end
  end
end

app/views/music_categories/index.html.erb
<h1>Listing music_categories</h1>

<table>
  <tr>
    <th>Music genre</th>
    <th>Music song</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @music_categories.each do |music_category| %>
  <tr>
    <td><%= music_category.music_genre %></td>
    <td><%= music_category.music_song %></td>
    <td><%= link_to 'Show', music_category %></td>
    <td><%= link_to 'Edit', edit_music_category_path(music_category) %></td>
    <td><%= link_to 'Destroy', music_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Music category', new_music_category_path %>

app/views/music_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Music genre:</b>
  <%= @music_category.music_genre %>
</p>

<p>
  <b>Music song:</b>
  <%= @music_category.music_song %>
</p>


<%= link_to 'Edit', edit_music_category_path(@music_category) %> |
<%= link_to 'Back', music_categories_path %>