config/routes.rb
Takeout::Application.routes.draw do
  root :to => 'welcome#show'

  resource :welcome

  resource :settings do
    member do
      get 'scan'
      get 'music_scan'
      get 'movies_scan'
    end
  end

  resources :music_members do
    member do
      get 'artists'
    end
    collection do
      get 'performers'
    end
  end

  resources :music_credits

  resources :music_images

  resource :music, :controller => 'music' do
    member do
      get 'artists'
      get 'albums'
      get 'tracks'
      get 'songs'
    end
  end
  resources :music_categories
  resources :music_genres, :only => [:index, :show] do
    member do
      get 'artists'
      get 'albums'
      get 'tracks'
      get 'songs'
    end
  end
  resources :music_songs do
    member do
      get 'stream'
      get 'cover'
    end
  end
  resources :music_albums, :only => [:index, :show] do
    collection do
      get 'released'
      get 'modified'
      get 'added'
    end
  end
  resources :music_artists do
    member do
      get 'songs'
    end
  end
  resources :music_search, :only => [:index]

  resources :movie_members do
    member do
      get 'movies'
    end
    collection do
      get 'actors'
      get 'directors'
      get 'producers'
      get 'writers'
    end
  end
  match 'movie_actors' => 'movie_members#actors'
  match 'movie_directors' => 'movie_members#directors'
  match 'movie_producers' => 'movie_members#producers'
  match 'movie_writers' => 'movie_members#writers'

  resources :movies, :only => [:index, :show] do
    member do
      get 'credits'
      get 'cast'
      get 'genres'
      get 'images'
      get 'stream'
    end
    collection do
      get 'released'
      get 'modified'
      get 'added'
    end
  end
  resources :movie_credits, :only => [:index, :show]
  resources :movie_collections, :only => [:index, :show]
  resources :movie_images, :only => [:index, :show]
  resources :movie_genres, :only => [:index, :show] do
    member do
      get 'movies'
    end
  end

end

app/models/movie_credit.rb
class MovieCredit < ActiveRecord::Base
  belongs_to :movie
  belongs_to :movie_member
  attr_accessible :character, :department, :job, :sort_order

  def name
    movie_member.name
  end

  def self.actors
    MovieCredit.where(:job => 'Actor').includes(:movie_member)
  end

  def self.directors
    MovieCredit.where(:job => 'Director').includes(:movie_member)
  end

  def self.writers
    MovieCredit.where(:job => 'Writer').includes(:movie_member)
  end

  def self.producers
    MovieCredit.includes(:movie_members).where(:job => 'Producer')
  end
end

app/controllers/movie_credits_controller.rb
class MovieCreditsController < ApplicationController
  def index
    @movie_credits = MovieCredit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movie_credits }
    end
  end

  def show
    @movie_credit = MovieCredit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie_credit }
    end
  end

  def actors
    @credit = MovieCredit.where(:job => 'Actor')
  end

  def directors
    @credit = MovieCredit.where(:job => 'Director')
  end

  def writers
    @credit = MovieCredit.where(:job => 'Writer')
  end

  def producers
    @credit = MovieCredit.where(:job => 'Producer')
  end
end

app/views/movie_credits/_credit.html.erb
<tr>
    <td><%= link_to credit.name, credit.movie_member %></td>
    <td><%= credit.job %></td>
    <td><%= credit.character %></td>
</tr>

app/views/movie_credits/index.html.erb
<h1><%= @movie.title %> <small>Credits</small></h1>
<div>
    <table class="table table-bordered">
        <tr><th>Member</th><th>Role</th><th>Character</th></tr>
        <%= render :collection => @movie_credits, :partial => 'movie_credits/credit' %>
    </table>
</div>

app/views/movie_credits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <img src="<%= @movie_credit.profile %>">
</p>

<p>
  <b>Name:</b>
  <%= @movie_credit.name %>
</p>

<p>
  <b>Job:</b>
  <%= @movie_credit.job %>
</p>

<p>
  <b>Department:</b>
  <%= @movie_credit.department %>
</p>

<p>
  <b>Character:</b>
  <%= @movie_credit.character %>
</p>

<p>
  <b>Order:</b>
  <%= @movie_credit.order %>
</p>

<p>
  <b>Profile:</b>
  <%= @movie_credit.profile %>
</p>

<p>
  <b>Movie:</b>
  <%= @movie_credit.movie %>
</p>


<%= link_to 'Edit', edit_movie_credit_path(@movie_credit) %> |
<%= link_to 'Back', movie_credits_path %>