config/routes.rb
Takeout::Application.routes.draw do
  root :to => 'welcome#show'

  resource :welcome

  resource :settings do
    member do
      get 'scan'
      get 'music_scan'
      get 'movies_scan'
    end
  end

  resources :music_members do
    member do
      get 'artists'
    end
    collection do
      get 'performers'
    end
  end

  resources :music_credits

  resources :music_images

  resource :music, :controller => 'music' do
    member do
      get 'artists'
      get 'albums'
      get 'tracks'
      get 'songs'
    end
  end
  resources :music_categories
  resources :music_genres, :only => [:index, :show] do
    member do
      get 'artists'
      get 'albums'
      get 'tracks'
      get 'songs'
    end
  end
  resources :music_songs do
    member do
      get 'stream'
      get 'cover'
    end
  end
  resources :music_albums, :only => [:index, :show] do
    collection do
      get 'released'
      get 'modified'
      get 'added'
    end
  end
  resources :music_artists do
    member do
      get 'songs'
    end
  end
  resources :music_search, :only => [:index]

  resources :movie_members do
    member do
      get 'movies'
    end
    collection do
      get 'actors'
      get 'directors'
      get 'producers'
      get 'writers'
    end
  end
  match 'movie_actors' => 'movie_members#actors'
  match 'movie_directors' => 'movie_members#directors'
  match 'movie_producers' => 'movie_members#producers'
  match 'movie_writers' => 'movie_members#writers'

  resources :movies, :only => [:index, :show] do
    member do
      get 'credits'
      get 'cast'
      get 'genres'
      get 'images'
      get 'stream'
    end
    collection do
      get 'released'
      get 'modified'
      get 'added'
    end
  end
  resources :movie_credits, :only => [:index, :show]
  resources :movie_collections, :only => [:index, :show]
  resources :movie_images, :only => [:index, :show]
  resources :movie_genres, :only => [:index, :show] do
    member do
      get 'movies'
    end
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  layout 'movies'

  def index
    @movies = Movie.order(:sort_title)

    respond_to do |format|
      format.html
      format.json { render json: @movies }
    end
  end

  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html { render template_name }
      format.json { render json: @movie }
    end
  end

  def posters
    @movie = Movie.find(params[:id])
    @movie_posters = @movie.movie_images.where(:type => 'poster')

    respond_to do |format|
      format.html { render 'movie_posters/index'}
      format.json { render json: @movie_posters }
    end
  end

  def backdrops
    @movie = Movie.find(params[:id])
    @movie_backdrops = @movie.movie_images.where(:type => 'backdrop')

    respond_to do |format|
      format.html { render 'movie_backdrops/index'}
      format.json { render json: @movie_backdrops }
    end
  end

  def credits
    @movie = Movie.find(params[:id])
    @movie_credits = @movie.movie_credits

    respond_to do |format|
      format.html { render 'movie_credits/index'}
      format.json { render json: @movie_credits }
    end
  end

  def cast
    @movie = Movie.find(params[:id])
    @movie_credits = @movie.cast

    respond_to do |format|
      format.html { render 'movie_credits/index'}
      format.json { render json: @movie_credits }
    end
  end

  def genres
    @movie = Movie.find(params[:id])
    @movie_genres = @movie.movie_genres

    respond_to do |format|
      format.html { render 'movie_genres/index'}
      format.json { render json: @movie_genres }
    end
  end

  after_filter :check_disposition

  def stream
    @movie = Movie.find(params[:id])
    send_file @movie.file_uri, :disposition => 'inline', :type => 'video/mp4'
    #response.headers['X-SendFile'] = @movie.file_uri
    #response.headers['Content-Type'] = 'video/x-matroska'
    #render :nothing => true
  end

  def check_disposition
    if request.headers['HTTP_USER_AGENT'] =~ /Silk-Accelerated/i
      response.headers.delete('Content-Disposition')
      response.headers.delete('Content-Transfer-Encoding')
    end
  end

  def released
    @movies = Movie.released(params[:id] || 100)
    respond_to do |format|
      format.html { render 'movies/index'}
      format.json { render json: @movies }
    end
  end

  def modified
    @movies = Movie.modified(params[:id] || 100)
    respond_to do |format|
      format.html { render 'movies/index'}
      format.json { render json: @movies }
    end
  end

  def added
    @movies = Movie.added(params[:id] || 100)
    respond_to do |format|
      format.html { render 'movies/index'}
      format.json { render json: @movies }
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def movie_image(image, options = {})
    if image and image.url
      image_tag(url_for(image), options)
    else
      ""
    end
  end

  def movie_thumb(movie, options = {})
    movie_image(movie.thumb, options)
  end

  def movie_cover(movie, options = {})
    movie_image(movie.cover, options)
  end

  def movie_backdrop(movie, options = {})
    movie_image(movie.backdrops.shuffle.first, options)
  end

  def movie_poster(movie, options = {})
    movie_image(movie.posters.shuffle.first, options)
  end

  def member_thumb(member, options = {})
    movie_image(member.thumb, options)
  end

  def member_profile(member, options = {})
    movie_image(member.profile, options)
  end

  def collection_thumb(collection, options = {})
    thumb = collection.thumb
    unless thumb
      thumb = collection.movies.shuffle.first.thumb
    end
    movie_image(thumb, options)
  end

  def collection_cover(collection, options = {})
    movie_image(collection.cover, options)
  end

  def collection_backdrop(collection, options = {})
    backdrops = collection.backdrops
    if backdrops.empty?
      backdrops = collection.movies.shuffle.first.backdrops
    end
    movie_image(backdrops.shuffle.first, options)
  end

  def collection_poster(collection, options = {})
    posters = collection.posters
    if posters.empty?
      posters = collection.movies.shuffle.first.posters
    end
    movie_image(posters.shuffle.first, options)
  end

  def genre_thumb(genre, options = {})
    movie_image(genre.movies.shuffle.first.thumb, options)
  end
end

app/views/movies/_index.html.erb
<%= render :collection => @movies, :partial => 'movie' %>

app/views/movies/_movie.html.erb
<%= link_to movie_cover(movie, :class => 'movie-cover'), movie %>

app/views/movies/_show.html.erb
<div>
    <%= movie_backdrop(@movie, :width => '100%', :height => '100%') %>
</div>

app/views/movies/_show2.html.erb
<div style="height:100%">
    <table border="0" height="100%">
        <tr>
            <td valign="top">
            </td>
            <td></td>
            <td valign="top"></td>
        </tr>
        <tr>
            <td valign="bottom" width="<%=@movie.cover.width%>">
                <div style="padding:10px">
                    <%= movie_cover(@movie, :class => 'movie-cover') %>
                </div>
            </td>
            <td></td>
            <td width="50%" valign="bottom">
                <div style="padding:10px">
                    <div class="movie-card">
                        <div>
                            <span class="movie-show-title"><%= @movie.title %></span>
                            <span class="movie-show-year">(<%= @movie.year %>)</span>
                        </div>
                        <div>
                            <span class="movie-show-tagline"><%= @movie.tagline %></span>
                        </div>
                        <hr>
                        <div>
                            <span class="movie-show-runtime"><%= @movie.runtime %> mins</span>,
                            <span class="movie-show-rating">Rated <%= @movie.rating.upcase %></span>
                        </div>
                        <p>

                        <p>
                        <div>
                            <span class="movie-show-heading">Genre:</span>
                            <span class="movie-show-genre"><%= @movie.genres.map { |genre| genre.name }.join(", ") %></span>
                        </div>
                        <p>
                        <div>
                            <span class="movie-show-heading">Director:</span>
                            <span class="movie-show-director"><%= @movie.director.name %></span>
                        </div>
                        <p>
                        <div>
                            <span class="movie-show-heading">Staring:</span>
                            <span class="movie-show-cast"><%= @movie.cast.limit(5).map { |actor| actor.name }.join(", ") %></span>
                        </div>
                        <hr>
                        <div>
                            <span class="movie-show-overview"><%= @movie.overview %></span>
                        </div>
                        <hr>
                        <div>
                            <span class="movie-show-url"><a href="<%= stream_movie_url @movie %>"><%= @movie.file_uri %></a></span>
                        </div>
                    </div>
                </div>
            </td>
        </tr>

    </table>
</div>
<div class="movie-backdrop">
    <%= movie_backdrop(@movie, :width => '100%', :height => '100%') %>
</div>

app/views/movies/_thumb.html.erb
<li class="span1">
    <%= link_to movie_thumb(thumb, :class => 'movie-cover'), thumb %>
</li>

app/views/movies/show.foo.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @movie.title %>
</p>

<p>
  <b>Alt title:</b>
  <%= @movie.alt_title %>
</p>

<p>
  <b>Sort title:</b>
  <%= @movie.sort_title %>
</p>

<p>
  <b>Url:</b>
  <%= @movie.url %>
</p>

<p>
  <b>Rating:</b>
  <%= @movie.rating %>
</p>

<p>
  <b>Runtime:</b>
  <%= @movie.runtime %>
</p>

<p>
  <b>Released:</b>
  <%= @movie.released %>
</p>

<p>
  <b>Imdb:</b>
  <%= @movie.imdb_id %>
</p>

<p>
    <b>Tmdb:</b>
    <%= @movie.tmdb_id %>
</p>

<p>
  <b>Overview:</b>
  <%= @movie.overview %>
</p>

<p>
  <b>Tagline:</b>
  <%= @movie.tagline %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

<img src="<%=@movie.movie_backdrops.first.url%>">

app/views/movies/show.html.erb
<h1><%= @movie.title %> <small><%= @movie.tagline %></small></h1>
<div style="position: relative; margin-bottom: 3px">
    <%= link_to movie_backdrop(@movie), stream_movie_url(@movie) %>
</div>
<div>
    <span class="label label-info">Rated <%= @movie.rating.upcase %></span>
    <span class="label label-info"><%= @movie.runtime %> mins</span>
    <span class="label label-info"><%= @movie.year %></span>
</div>
<p></p>
<div>
    <p><%= @movie.overview %></p>

    <dl>
        <dt>Staring</dt>
        <dd><%= raw @movie.cast.limit(5).map { |credit| link_to credit.name, credit.movie_member }.join(", ") %></dd>

        <dt>Director</dt>
        <dd><%= raw @movie.directors.map { |credit| link_to credit.name, credit.movie_member }.join(", ") %></dd>

        <dt>Genre</dt>
        <dd><%= raw @movie.genres.map { |genre| link_to genre.name, genre }.join(", ") %></dd>
    </dl>
</div>