config/routes.rb
Takeout::Application.routes.draw do
  root :to => 'welcome#show'

  resource :welcome

  resource :settings do
    member do
      get 'scan'
      get 'music_scan'
      get 'movies_scan'
    end
  end

  resources :music_members do
    member do
      get 'artists'
    end
    collection do
      get 'performers'
    end
  end

  resources :music_credits

  resources :music_images

  resource :music, :controller => 'music' do
    member do
      get 'artists'
      get 'albums'
      get 'tracks'
      get 'songs'
    end
  end
  resources :music_categories
  resources :music_genres, :only => [:index, :show] do
    member do
      get 'artists'
      get 'albums'
      get 'tracks'
      get 'songs'
    end
  end
  resources :music_songs do
    member do
      get 'stream'
      get 'cover'
    end
  end
  resources :music_albums, :only => [:index, :show] do
    collection do
      get 'released'
      get 'modified'
      get 'added'
    end
  end
  resources :music_artists do
    member do
      get 'songs'
    end
  end
  resources :music_search, :only => [:index]

  resources :movie_members do
    member do
      get 'movies'
    end
    collection do
      get 'actors'
      get 'directors'
      get 'producers'
      get 'writers'
    end
  end
  match 'movie_actors' => 'movie_members#actors'
  match 'movie_directors' => 'movie_members#directors'
  match 'movie_producers' => 'movie_members#producers'
  match 'movie_writers' => 'movie_members#writers'

  resources :movies, :only => [:index, :show] do
    member do
      get 'credits'
      get 'cast'
      get 'genres'
      get 'images'
      get 'stream'
    end
    collection do
      get 'released'
      get 'modified'
      get 'added'
    end
  end
  resources :movie_credits, :only => [:index, :show]
  resources :movie_collections, :only => [:index, :show]
  resources :movie_images, :only => [:index, :show]
  resources :movie_genres, :only => [:index, :show] do
    member do
      get 'movies'
    end
  end

end

app/views/shared/_footer.html.erb
<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="/bootstrap/js/bootstrap.js"></script>
<script src="/javascripts/jquery.jscroll.js"></script>
<script src="/javascripts/jquery.shuffle.js"></script>
<script src="/javascripts/audio.js"></script>
<script type="text/javascript">
    $().ready(function() {
        $(".scroll").jScroll({ noscroll : ".noscroll"});
        doAudioPlayer();
    });
</script>
</body>
</html>

app/views/shared/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><%= t :takeout %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>
    <link href="/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag 'music' %>
    <%= stylesheet_link_tag 'movies' %>
</head>

<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/"><%= t :takeout %></a>
            <div class="nav-collapse collapse" >
                <ul class="nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t :music %> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to t(:artists), music_artists_path %></li>
                            <li><%= link_to t(:albums), music_albums_path %></li>
                            <li><%= link_to t(:genres), music_genres_path %></li>
                            <li><%= link_to t(:new_releases), released_music_albums_path %></li>
                            <li><%= link_to t(:recently_added), modified_music_albums_path %></li>
                            <li><%= link_to t(:performers), performers_music_members_path %></li>
                        </ul>
                    </li>
                    <li class="divider-vertical"></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t :movies %> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to t(:all_movies), movies_path %></li>
                            <li><%= link_to t(:collections), movie_collections_path %></li>
                            <li><%= link_to t(:genres), movie_genres_path %></li>
                            <li><%= link_to t(:new_releases), released_movies_path %></li>
                            <li><%= link_to t(:recently_added), modified_movies_path %></li>
                            <li><%= link_to t(:actors), movie_actors_path %></li>
                            <li><%= link_to t(:directors), movie_directors_path %></li>
                            <li><%= link_to t(:producers), movie_producers_path %></li>
                            <li><%= link_to t(:writers), movie_writers_path %></li>
                        </ul>
                    </li>
                    <li class="divider-vertical"></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t :settings %> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to 'Update Music', music_scan_settings_path %></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
            <div class="nav-collapse collapse" >
                <form class="navbar-form pull-right" action="/music_search">
                    <input class="span2" type="text" name="q" placeholder="Search">
                    <button class='btn add-on'><i class="icon-search"></i></button>
                </form>
            </div>
        </div>
    </div>
</div>